name: caritakeun_kelompok4
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.0.5
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.4
  fluttertoast: ^7.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:     
    - assets/img/signin.png
    - assets/img/signup.png

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
    - family: RajdhaniBold
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
    - family: RajdhaniSemiBold
      fonts:
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
    - family: RajdhaniLight
      fonts:
        - asset: assets/fonts/Rajdhani-Light.ttf
    - family: RajdhaniMedium
      fonts:
        - asset: assets/fonts/Rajdhani-Medium.ttf
  uses-material-design: true
